sudo: required

language: python
python:
  # We don't actually use the Travis Python (since we are on conda), but this keeps it organized.
  - "3.6"

## Download data bundles. (skipping this because of lack of disk space on Travis)
#before_install:
#  - cd ..
#  - git clone https://github.com/circulosmeos/gdown.pl
#  - gdown.pl/gdown.pl https://drive.google.com/file/d/1cGBAmAh5t4miIeRrrd0zHsPCFToOr0Lf/view pcgr.databundle.grch37.tgz
#  - gzip -dc pcgr.databundle.grch37.tgz | tar xvf -


install:
  # Installing (the non-docker version)
  - source install_no_docker/install.sh

script:
  - source install_no_docker/load_pcgr.sh
  # (Skipping running an actual test because we don't have enough Travis disk space for full data bundles)
  # - python pcgr.py \
  #   --input_vcf examples/tumor_sample.COAD.vcf.gz \
  #   --input_cna examples/tumor_sample.COAD.cna.tsv \
  #   . \
  #   examples \
  #   grch37 \
  #   examples/pcgr_conf.COAD.toml \
  #   tumor_sample.COAD
  #   --no-docker
