name: pcgr

channels:
  - bioconda
  - conda-forge
  - vladsaveliev
  - defaults
  - anaconda

dependencies:
  #
  # PCGR: python
  - python>=3.6
  - pip
  - numpy
  - cython
  - scipy
  - pandas
  - cyvcf2
  - toml
  #
  # PCGR: other tools
  - tabix
  - samtools
  - bedtools
  - vcfanno
  - vt
  - htslib
  - vcf2maf
  - nlopt
  #
  # Perl (for VEP)
  - perl-bioperl
  - ensembl-vep>=94
  #
  # PCGR: R packages
  - pandoc==2.3.1
  - r-base==3.4.1
  - bioconductor-biocinstaller
  - libgfortran-ng  # to fix -libgfortran error, thanks @pdiakumis
  - r-purrr>=0.2.4  # to force the one from conda-forge to address this issue https://github.com/jbkunst/highcharter/issues/285
  - r-dplyr
  - r-devtools
  - r-stringr
  - r-tidyr
  - r-httr
  - r-git2r
  - r-data.table
  - r-magrittr
  - r-htmltools
  - r-caret
  - r-randomforest
  - r-plotly
  - r-rcpptoml
  - r-ggplot2
  - r-dt
  - r-stringi>=1.1.7  # for pcgrr
  - r-htmlwidgets>=1.0  # requirement for DT (by default, 0.9 is getting installed)
  - r-crosstalk
  - r-deconstructsigs
  - r-knitr>=1.17
  - r-rmarkdown
  - r-collapsibletree  # for CELLector
  - r-data.tree  # for collapsibleTree
  - r-igraph     # for collapsibleTree
  - r-configr    # -c vladsaveliev
  - r-sunburstr  # for CELLector, -c vladsaveliev
  - r-arules     # for CELLector, -c vladsaveliev
  - r-rlogging
  - bioconductor-variantannotation
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-genomeinfodb
  - bioconductor-genomicranges  # GenomicRangesS4Vectors
  - bioconductor-regioner
  - bioconductor-mutationalpatterns
  - gdown
